### ISSUE TITLE
footway tunnels have no special transparentish rendering, unlike roads

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#114]
It would be desirable to modify them so such rendering would be present.

related to #40

**Comment by Helium314** [comment]
Works when adding
```
            path-tunnel:
                filter: { structure: tunnel }
                draw:
                    lines-road-style:
                        order: 20
                        style: tunnel-way
                        color: global.tunnel_color
                        outline:
                            order: 21
```
below https://github.com/streetcomplete/streetcomplete-mapstyle/blob/2ecce80b365b2eea1e1351ad3abe5f8b355f9a5b/layers/roads.yaml#L96-L102
