### ISSUE TITLE
Tunnels are too prominent

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#48]
Tunnels are too prominent, too solid. 
Only the outline of the tunnel should be shown half-transparent and dashed, but the line should not be filled - or if filled, with something along the lines like 90% transparency.
Also, the outlines of normal roads and those of tunnels are merged, this looks quite weird.

![untitled](https://user-images.githubusercontent.com/4661658/36073656-7d1d7ae0-0f34-11e8-863f-67b58c54fb74.png)

**Comment by ENT8R** [comment]
The problem is that I have absolutely no idea how to show only the outline but not the whole tunnel because the tunnel will always be drawn by default...

**Comment by westnordost** [comment]
Draw it with 100% transparency?

**Comment by ENT8R** [comment]
Adding
```yaml
tunnel:
  filter: { is_tunnel: true }
  draw:
    lines:
      color: [0, 0, 0, 0]
      outline:
        dash: [0.6,0.4]
        color: [0.000, 0.000, 0.000, 1.00]
        order: 400
        width: function () { return 1*4 * Math.log($zoom); }
```
results in
<img src="https://user-images.githubusercontent.com/25306497/36075853-a52470f0-0f54-11e8-8838-d827baa690b5.png" width="400px">

**Comment by westnordost** [comment]
Don't use the "opaque" (default) draw mode for translucent stuff. Try `inlay`.

**Comment by ENT8R** [comment]
Looks still like this:
<img src="https://user-images.githubusercontent.com/25306497/36076057-ab3a34b8-0f57-11e8-9f65-39b7dbe892f0.png" width="400px">

**Comment by westnordost** [comment]
How about other blend modes?

**Comment by ENT8R** [comment]
The same result...

**Comment by ENT8R** [comment]
There is not even a visible effect when switching the modes...

**Comment by westnordost** [comment]
Perhaps then disable rendering tunnels again for now. There is a rat-tail attached to that feature. I.e. look at Bonn Central Station:

![bonn](https://user-images.githubusercontent.com/4661658/36444259-481cd482-167b-11e8-94df-ada9346225c9.png)

**Comment by ENT8R** [comment]
Alright.

**Comment by westnordost** [comment]
Okay, the goal is to make the line fill of tunnels half-transparent or even fully-transparent+preserving the line outline.

I also had a go but did not succeed. I think why the translucent blend mode does not seem to work on tunnels is because the parent rule already defines a (white) color for the road. The half-transparent white of tunnels then just adds to the white of the road.

I tried to not define the road color in the parent draw rule (for `roads`) but in a rule like this:
```
        non-tunnel:
            filter: { not: { is_tunnel: true }}
            draw:
                lines:
                    color: global.road_color
```
(to achieve the line for tunnels not being filled but just the outline drawn)
that works insofar as this works for all other roads that are not tunnels. However, tunnels are not drawn at all this way - the `road-outline` rule further below does not draw. Perhaps because in tangram-es, if no color for the line fill is specified, also the outline is not drawn.

Adding
```
        tunnel:
            filter: { is_tunnel: true }
            draw:
                tunnel-way:
                    color: rgba(255,0,255,0.5)

styles:
    tunnel-way:
        base: lines
        blend: translucent
        blend_order: 1
```
_does_ draw tunnels (for testing: pink), but not translucent but opaque.

@matteblair, do you know what I am doing wrong? My goal is to draw tunnels with a (half-)transparent fill (while keeping the outline at full opaqueness, if possible). Though, I am failing to draw the tunnels half-transparent in the first place.
[Roads style](https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/layers/roads.yaml)

**Comment by matteblair** [comment]
I think what's going to work best here is a `lines` style using the `translucent` blend mode:

```yaml
styles:
    tunnel-style:
        base: lines
        blend: translucent
```
Paired with draw rules that set a low (or zero) fill opacity and a high outline opacity:
```yaml
layers:
    roads:
        data: { source: nextzen}
        filter: { not: { kind: [rail, ferry] } }
        tunnel:
            filter: {is_tunnel: true }
            draw:
                lines:
                    style: tunnel-style
                    color: [0., 1., 0., 0.1]
                    width: 7px
                    order: 6
                    outline:
                        color: [.8, .8, .8, 1.]
                        width: 3px
```
Let me know if that looks better!

**Comment by westnordost** [comment]
Oh right, I tried your suggestion, and it looks pretty good now. I think what I did wrong was to write

```
        tunnel:
            filter: { is_tunnel: true }
            draw:
                tunnel-way:
                    color: rgba(255,0,255,0.5)
```

instead of

```
        tunnel:
            filter: { is_tunnel: true }
            draw:
               lines:
                    style: tunnel-way
                    color: rgba(255,0,255,0.5)
```
