### ISSUE TITLE
missing 512 in tile server url

### ISSUE THREAD

**Issue by Akasch** [ENT8R/streetcomplete-mapstyle#53]
was there a reason behind the dropping of the 512 in the tileserverurl? I found out while looking into the server logs and wondering why some tiles there not served from prerendered files (I have fixed it with a rewrite on the server, but for caching a consistent naming would be good).

```
sources:
    mapzen:
        type: MVT
        url: https://tiles.map-data.de/vector/v1/all/{z}/{x}/{y}.mvt
```

vs.

```
sources:
    mapzen:
        type: MVT
        url: https://tiles.map-data.de/vector/v1/512/all/{z}/{x}/{y}.mvt
```

from older StreetComplete Versions
