### ISSUE TITLE
Display access of roads, one-ways, barriers

### ISSUE THREAD

**Issue by westnordost** [ENT8R/streetcomplete-mapstyle#64]
While testing StreetComplete extensively during my last vacation, I found that there are a few things which should additionally be displayed:

1. one-ways (with arrows): It is easy to see with one look on the map whether a road is a oneway or not, giving the surveyor the opportunity to create a note if reality does not coincide with the map. Also, this is still a property of the road, so other than POIs which are not displayed, there may be the expectation anyway that one-ways are marked somehow.
2. private/destination/access=no roads: Same argumentation as above. Additionally, StreetComplete should not get the user into trouble and since the user is using StreetComplete also for orientation during survey, it should not appear as if private roads are ok to go through. If possible, private roads could be hatched with red stripes (using a shader?) and destination roads with a similar pattern but with a less "forbidden" color.
3. Barriers, both for cars (bollards etc) and possible for everyone (gates etc) should be shown. The former could perhaps be a dot, the latter a larger square? Just an idea.
4. Turning circles should probably also be rendered as white dots, because this is also part of the geometry of the road.

I can work on this. I just wanted to post this here first to get feedback from you about these.

**Comment by ENT8R** [comment]
Sounds all reasonable! Thank you for offering to do this :+1:

**Comment by matkoniecz** [comment]
From what I see map in Poland is not updated.

**Comment by westnordost** [comment]
> Note that access tag may be missing in tile data if it is not including tilezen/vector-datasource#1328 (I think that Tilezen went bankrupt after merging this PR but before version with that change was released).

But the project is still quite active. Last release was a month ago. Didn't you know?

**Comment by matkoniecz** [comment]
> But the project is still quite active. Last release was a month ago. Didn't you know?

I didn't know, thanks! I will look at whatever this data is now in tiles available for StreetComplete, maybe I can finally finish my map style :)

**Comment by westnordost** [comment]
Experiment with hatching. But I think this is not so good after all, because roads that run in a 45° angle North would have a very odd hatching.  Will experiment the hatching according to the orientation of the way (first experiment also looked not so good though)

```
sources:
    nextzen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.topojson

styles:
    hatching-overlay:
        base: lines
        blend: translucent
        shaders:
            uniforms:
                u_repeat: 0.8
                u_width: 0.1
            blocks:
                color: |
                    vec4 p = worldPosition();
                    color.a = mix(0., 1., smoothstep(0.,1.,u_width+.5*sin(u_repeat * (p.y - p.x) / u_meters_per_pixel)));

layers:
    roads:
        data: { source: nextzen}
        draw:
            lines:
                style: hatching-overlay
                order: 4
                color: [0.8,0.8,0.8,0.0]
                width: 10px
```
