### ISSUE TITLE
Steps on a bridge displayed like path

### ISSUE THREAD

**Issue by Helium314** [ENT8R/streetcomplete-mapstyle#93]
Ways with highway=steps and bridge=yes are displayed in the same style as paths.
I find this somewhat confusing... is it done on purpose?

**Comment by Helium314** [comment]
Works when adding
```
                bridge-steps:
                    filter: { structure: bridge }
                    draw:
                        step_dashes:
                            order: 41
```
below https://github.com/streetcomplete/streetcomplete-mapstyle/blob/2ecce80b365b2eea1e1351ad3abe5f8b355f9a5b/layers/roads.yaml#L103-L110
